# Assignment 1



 * Name: Shlok Nikam
* PRN: 12414145



*   Batch: 2
*   Division: D



*   Branch: CSE(AI)
*   Date: 6/1/2026

Perform the following operations using Python on suitable data sets: a. Read data from different formats (like csv, xls) b. Find Shape of Data c. Find Missing Values d. Find data type of each column e. Finding out Zero's f. Indexing and selecting data, sort data, g. Describe attributes of data, checking data types of each column, h. counting unique values of data, format of each column, converting variable data type (e.g. from long to short, vice versa)

Read the csv file, print first 5 and last 5 rows of data

Imports

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('house_prices_practice.csv')
df.head()
df.tail()

Find Shape of Data

In [ ]:
df.shape

(300, 10)

Find Missing Values

In [ ]:
df.isnull().sum()

Id              0
OverallQual     0
GrLivArea       0
GarageCars      0
TotalBsmtSF     0
YearBuilt       0
FullBath        0
BedroomAbvGr    0
LotArea         0
SalePrice       0
dtype: int64

Find Data Type of Each Column

In [ ]:
df.dtypes

Id              int64
OverallQual     int64
GrLivArea       int64
GarageCars      int64
TotalBsmtSF     int64
YearBuilt       int64
FullBath        int64
BedroomAbvGr    int64
LotArea         int64
SalePrice       int64
dtype: object

Finding Zero Values in Dataset

In [ ]:
(df == 0).sum()

Id               0
OverallQual      0
GrLivArea        0
GarageCars      91
TotalBsmtSF      0
YearBuilt        0
FullBath        76
BedroomAbvGr     0
LotArea          0
SalePrice        0
dtype: int64

All cols, from rows 0 to 4

In [ ]:
df.loc[0:4, :] #all cols, from rows 0 to 4

,Id,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
0,1,7,1560,0,1658,1969,2,1,8059,177106
1,2,4,2827,2,1319,2012,3,4,13530,301044
2,3,8,3920,0,841,2010,1,4,9010,360609
3,4,5,3044,0,1058,1998,0,4,13207,240556
4,5,7,801,1,2428,2020,0,1,9117,193656

dfiloc05

In [ ]:
df.iloc[0:5, 0:3] #first 5 rows first 3 cols

   Id  OverallQual  GrLivArea
0   1            7       1560
1   2            4       2827
2   3            8       3920
3   4            5       3044
4   5            7        801

df_sorted

In [ ]:
df_sorted = df.sort_values(by=df.columns[1])
df_sorted.head()

,Id,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
25,26,1.0,1846,1,580,2012,0,1,10234,129364
275,276,1.0,2724,0,685,2005,0,2,2560,158055
266,267,1.0,1796,1,2234,1998,2,1,10453,203881
268,269,1.0,1095,0,501,1961,3,5,10597,82494
276,277,1.0,2135,0,774,2012,0,5,14329,155462

dfdescribe

In [ ]:
df.describe()

,Id,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,150.500000,5.326667,2307.386667,1.330000,1468.796667,1986.163333,1.523333,2.926667,8969.453333,252262.903333
std,86.746758,2.873001,1042.561303,1.109898,672.333705,21.377089,1.131543,1.456604,3753.531132,74998.055214
min,1.000000,1.000000,504.000000,0.000000,303.000000,1950.000000,0.000000,1.000000,2009.000000,82494.000000
25%,75.750000,3.000000,1392.250000,0.000000,903.000000,1967.000000,0.000000,2.000000,5996.250000,190355.250000
50%,150.500000,5.000000,2265.500000,1.000000,1502.000000,1986.000000,2.000000,3.000000,9031.000000,251292.500000
75%,225.250000,8.000000,3306.500000,2.000000,2129.500000,2004.250000,3.000000,4.000000,12316.000000,307105.000000
max,300.000000,10.000000,3998.000000,3.000000,2492.000000,2023.000000,3.000000,5.000000,14987.000000,435291.000000

dfinfo

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            300 non-null    int64
 1   OverallQual   300 non-null    int64
 2   GrLivArea     300 non-null    int64
 3   GarageCars    300 non-null    int64
 4   TotalBsmtSF   300 non-null    int64
 5   YearBuilt     300 non-null    int64
 6   FullBath      300 non-null    int64
 7   BedroomAbvGr  300 non-null    int64
 8   LotArea       300 non-null    int64
 9   SalePrice     300 non-null    int64
dtypes: int64(10)
memory usage: 23.6 KB

dfnunique

In [ ]:
df.nunique()

Id              300
OverallQual      10
GrLivArea       287
GarageCars        4
TotalBsmtSF     278
YearBuilt        73
FullBath          4
BedroomAbvGr      5
LotArea         296
SalePrice       300
dtype: int64

Loop

In [ ]:
for col in df.columns:
    print(col, ":", df[col].dtype)

Id : int64
OverallQual : int64
GrLivArea : int64
GarageCars : int64
TotalBsmtSF : int64
YearBuilt : int64
FullBath : int64
BedroomAbvGr : int64
LotArea : int64
SalePrice : int64

Convert first numeric column to int

In [ ]:
# Convert first numeric column to int
df[df.columns[1]] = df[df.columns[1]].astype(int)

df.dtypes

Id              int64
OverallQual     int64
GrLivArea       int64
GarageCars      int64
TotalBsmtSF     int64
YearBuilt       int64
FullBath        int64
BedroomAbvGr    int64
LotArea         int64
SalePrice       int64
dtype: object

dfdfcolumns1

In [ ]:
df[df.columns[1]] = df[df.columns[1]].astype(float)
df.dtypes

Id                int64
OverallQual     float64
GrLivArea         int64
GarageCars        int64
TotalBsmtSF       int64
YearBuilt         int64
FullBath          int64
BedroomAbvGr      int64
LotArea           int64
SalePrice         int64
dtype: object

df_drop_col

In [ ]:
df_drop_col = df.drop(columns=[df.columns[4]])
df_drop_col.head()

,Id,OverallQual,GrLivArea,GarageCars,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
0,1,7.0,1560,0,1969,2,1,8059,177106
1,2,4.0,2827,2,2012,3,4,13530,301044
2,3,8.0,3920,0,2010,1,4,9010,360609
3,4,5.0,3044,0,1998,0,4,13207,240556
4,5,7.0,801,1,2020,0,1,9117,193656

df_drop_row

In [ ]:
df_drop_row = df.drop(index=0)
df_drop_row.head()

,Id,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
1,2,4.0,2827,2,1319,2012,3,4,13530,301044
2,3,8.0,3920,0,841,2010,1,4,9010,360609
3,4,5.0,3044,0,1058,1998,0,4,13207,240556
4,5,7.0,801,1,2428,2020,0,1,9117,193656
5,6,10.0,680,1,2480,1950,2,1,13081,213952

df_no_dup

In [ ]:
df_no_dup = df.drop_duplicates()
df_no_dup.head()

,Id,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
0,1,7.0,1560,0,1658,1969,2,1,8059,177106
1,2,4.0,2827,2,1319,2012,3,4,13530,301044
2,3,8.0,3920,0,841,2010,1,4,9010,360609
3,4,5.0,3044,0,1058,1998,0,4,13207,240556
4,5,7.0,801,1,2428,2020,0,1,9117,193656

Rename column

In [ ]:
df_rename = df.rename(columns={df.columns[0]:"NewName1", df.columns[1]:"NewName2"})
df_rename.head()

,NewName1,NewName2,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
0,1,7.0,1560,0,1658,1969,2,1,8059,177106
1,2,4.0,2827,2,1319,2012,3,4,13530,301044
2,3,8.0,3920,0,841,2010,1,4,9010,360609
3,4,5.0,3044,0,1058,1998,0,4,13207,240556
4,5,7.0,801,1,2428,2020,0,1,9117,193656

grouped

In [ ]:
grouped = df.groupby(df.columns[0]).mean()
grouped

,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,YearBuilt,FullBath,BedroomAbvGr,LotArea,SalePrice
Id,,,,,,,,,
1,7.0,1560.0,0.0,1658.0,1969.0,2.0,1.0,8059.0,177106.0
2,4.0,2827.0,2.0,1319.0,2012.0,3.0,4.0,13530.0,301044.0
3,8.0,3920.0,0.0,841.0,2010.0,1.0,4.0,9010.0,360609.0
4,5.0,3044.0,0.0,1058.0,1998.0,0.0,4.0,13207.0,240556.0
5,7.0,801.0,1.0,2428.0,2020.0,0.0,1.0,9117.0,193656.0
...,...,...,...,...,...,...,...,...,...
296,1.0,3495.0,1.0,1792.0,1954.0,2.0,5.0,4978.0,250604.0
297,5.0,3438.0,3.0,1266.0,2003.0,0.0,1.0,9373.0,329906.0
298,6.0,1992.0,0.0,1148.0,1996.0,1.0,1.0,7907.0,184623.0
299,3.0,3722.0,1.0,1407.0,1998.0,1.0,1.0,8097.0,303345.0
300,9.0,1667.0,0.0,988.0,1958.0,2.0,1.0,14553.0,204982.0

dfdfcolumns0value_counts

In [ ]:
df[df.columns[0]].value_counts()

Id
300    1
1      1
2      1
3      1
4      1
      ..
17     1
16     1
15     1
14     1
13     1
Name: count, Length: 300, dtype: int64

Sample Pandas DataFrame (custom)

In [ ]:
data = {
    'StudentID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115],
    'NAME': ['Aarav', 'Diya', 'Rohan', 'Sneha', 'Karan', 'Isha', 'Arjun', 'Pooja', 'Rahul', 'Neha',
             'Aman', 'Priya', 'Sahil', 'Ananya', 'Vikram'],
    'AGE': [19, 20, 18, 21, 20, 19, 22, 21, 20, 19, 21, 22, 20, 18, 23],
    'GENDER': ['M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M'],
    'DEPARTMENT': ['CSE', 'IT', 'CSE', 'ECE', 'ME', 'CSE', 'IT', 'ECE', 'ME', 'CSE',
                   'IT', 'ECE', 'CSE', 'ME', 'IT'],
    'MARKS': [85, 90, 78, np.nan, 72, 95, 80, 84, np.nan, 92, 76, 89, 83, 68, 91],
    'ATTENDANCE': [92, 95, 88, 90, np.nan, 98, 89, 91, 80, 96, np.nan, 93, 90, 82, 94],
    'INTERNSHIP': ['Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes',
                   'No', 'Yes', 'Yes', 'No', 'Yes']
}



df2 = pd.DataFrame(data)
print(df2)

    StudentID    NAME  AGE GENDER DEPARTMENT  MARKS  ATTENDANCE INTERNSHIP
0         101   Aarav   19      M        CSE   85.0        92.0        Yes
1         102    Diya   20      F         IT   90.0        95.0        Yes
2         103   Rohan   18      M        CSE   78.0        88.0         No
3         104   Sneha   21      F        ECE    NaN        90.0        Yes
4         105   Karan   20      M         ME   72.0         NaN         No
5         106    Isha   19      F        CSE   95.0        98.0        Yes
6         107   Arjun   22      M         IT   80.0        89.0         No
7         108   Pooja   21      F        ECE   84.0        91.0        Yes
8         109   Rahul   20      M         ME    NaN        80.0         No
9         110    Neha   19      F        CSE   92.0        96.0        Yes
10        111    Aman   21      M         IT   76.0         NaN         No
11        112   Priya   22      F        ECE   89.0        93.0        Yes
12        113   Sahil   20      M        CSE   83.0        90.0        Yes
13        114  Ananya   18      F         ME   68.0        82.0         No
14        115  Vikram   23      M         IT   91.0        94.0        Yes